#!/bin/bash
# -r readonly.
# -i integer.
# -a array
# -f list functions
# -x access outside the script

func1()
{
    echo This is a function.
}

declare -f

echo

declare -i var1
var1=231
echo "var1 declared as $var1"
var1=var1+1
echo "var1 incremented by 1 is $var1."
# Attept to change variable declared as integer.
echo "Attept to change var1 to floating point value, 231.1."
var1=231.1
echo "var1 is still $var1"

echo

declare -r var2=12.34

echo "var2 declared as $var2"
var2=12.35

echo "var2 is still $var2"

exit 0
